### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Exalm** [flathub/org.gnome.Books#1]
Same as in https://github.com/flathub/org.gnome.Documents/issues/1

**Comment by Exalm** [comment]
Actually, it might be https://bugzilla.gnome.org/show_bug.cgi?id=793489, see https://github.com/flathub/org.gnome.Documents/issues/1#issuecomment-372718007 and https://github.com/flathub/org.gnome.Documents/issues/1#issuecomment-372725024

**Comment by hadess** [comment]
Should be fixed since 3.30.1, please reopen if not.
