### ISSUE TITLE
Title bar grayed, nothing can be done

### ISSUE THREAD

**Issue by marcosps** [flathub/org.gnome.Books#14]
App opens fine, with some warnings:
(org.gnome.Books:2): Gtk-WARNING **: 13:00:32.891: Locale not supported by C library.
        Using the fallback 'C' locale.

(org.gnome.Books:2): Tracker-WARNING **: 13:00:33.039: Error parsing miner .desktop file: No such file or directory

But so far, nothing can be done. The title bar is disabled, even the menu is disabled (to check app version etc..)
![Screenshot from 2019-05-13 13-04-14](https://user-images.githubusercontent.com/1039418/57636497-a1f51280-757f-11e9-923c-d65877230cdd.png)

**Comment by marcosps** [comment]
Flatpak 1.2.4
NAME="openSUSE Tumbleweed"
# VERSION="20190428"

**Comment by johnfactotum** [comment]
This is an issue with Gnome Books itself, not just the Flatpak. It has been reported here: https://gitlab.gnome.org/GNOME/gnome-books/issues/30

**Comment by marcosps** [comment]
@johnfactotum thanks, so I'll close this issue here.
